"""create packages table

Revision ID: 0e79775c84c4
Revises: 
Create Date: 2024-12-11 20:14:10.462121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e79775c84c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'packages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sender_name', sa.String(length=20), nullable=False),
        sa.Column('recipient_name', sa.String(length=20), nullable=False),
        sa.Column('origin', sa.String(length=20), nullable=False),
        sa.Column('destination', sa.String(length=20), nullable=False),
        sa.Column('express_shipping', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_recipient'), ['recipient_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_sender_name'), ['sender_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_sender_name'))
        batch_op.drop_index(batch_op.f('ix_packages_recipient_name'))
        batch_op.drop_index(batch_op.f('ix_packages_origin'))
        batch_op.drop_index(batch_op.f('ix_packages_destination'))

    op.drop_table('packages')
    # ### end Alembic commands ###
